ARG SOURCE_REPOSITORY=ghcr.io/cshum/imagor-base
ARG SOURCE_TAG=latest
ARG SDK_TAG=${SOURCE_TAG}-sdk

FROM ${SOURCE_REPOSITORY}:${SDK_TAG} AS sdk

FROM ${SOURCE_REPOSITORY}:${SOURCE_TAG}

COPY --from=sdk /opt/imagor /opt/imagor

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    git \
    libaom-dev \
    libcairo2-dev \
    libcfitsio-dev \
    libcgif-dev \
    libdav1d-dev \
    libdeflate-dev \
    libde265-dev \
    libexpat1-dev \
    libexif-dev \
    libfontconfig1-dev \
    libfftw3-dev \
    libfreetype-dev \
    libfribidi-dev \
    libgsf-1-dev \
    libharfbuzz-dev \
    libheif-dev \
    libheif-plugin-aomenc \
    libheif-plugin-x265 \
    libimagequant-dev \
    libjpeg-turbo8-dev \
    libjxl-dev \
    liblcms2-dev \
    liblerc-dev \
    liblzma-dev \
    libmagickwand-dev \
    libmatio-dev \
    libopenexr-dev \
    libopenjp2-7-dev \
    libopenslide-dev \
    liborc-0.4-dev \
    libpango1.0-dev \
    libpixman-1-dev \
    libpng-dev \
    libpoppler-glib-dev \
    libraw-dev \
    librsvg2-dev \
    libspng-dev \
    libtiff-dev \
    libvorbis-dev \
    libvpx-dev \
    libwebp-dev \
    libx264-dev \
    libx265-dev \
    libxml2-dev \
    libzstd-dev \
    pkg-config \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /src
CMD ["bash"]
