ARG SOURCE_REPOSITORY=ghcr.io/cshum/imagor-base
ARG SOURCE_TAG=latest
ARG SOURCE_DEV_TAG=${SOURCE_TAG}-dev

FROM ${SOURCE_REPOSITORY}:${SOURCE_DEV_TAG} AS builder

COPY . /tmp/imagor-base

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    ca-certificates \
    curl \
    nasm \
    pkg-config \
    yasm \
    libaom-dev \
    libdav1d-dev \
    librtmp-dev \
    libtheora-dev \
    libvorbis-dev \
    libvpx-dev \
    libwebp-dev \
    libx264-dev \
    libx265-dev \
    libnuma-dev \
    xz-utils \
  && chmod +x /tmp/imagor-base/*.sh \
  && /tmp/imagor-base/build-ffmpeg.sh \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/imagor-base

FROM ${SOURCE_REPOSITORY}:${SOURCE_TAG} AS final

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    libaom3 \
    libdav1d7 \
    libnuma1 \
    librtmp1 \
    libtheora0 \
    libvorbis0a \
    libvorbisenc2 \
    libvpx9 \
    libwebp7 \
    libx264-164 \
    libx265-199 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/imagor/bin /opt/imagor/bin
COPY --from=builder /opt/imagor/lib /opt/imagor/lib

RUN rm -rf /opt/imagor/lib/pkgconfig /opt/imagor/lib/cmake

ENV PKG_CONFIG_PATH=/opt/imagor/lib/pkgconfig
ENV CGO_CFLAGS=-I/opt/imagor/include
ENV CGO_LDFLAGS="-L/opt/imagor/lib -Wl,-rpath,/opt/imagor/lib"
ENV LD_LIBRARY_PATH=/opt/imagor/lib
ENV FONTCONFIG_PATH=/etc/fonts

WORKDIR /src
CMD ["bash"]

FROM final AS sdk

COPY --from=builder /opt/imagor /opt/imagor

FROM sdk AS dev

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    git \
    libaom-dev \
    libcfitsio-dev \
    libcgif-dev \
    libdav1d-dev \
    libdeflate-dev \
    libexif-dev \
    libfftw3-dev \
    libgsf-1-dev \
    libheif-plugin-aomenc \
    libheif-plugin-x265 \
    libimagequant-dev \
    libjpeg-turbo8-dev \
    libjxl-dev \
    liblcms2-dev \
    liblerc-dev \
    liblzma-dev \
    libmagickwand-dev \
    libmatio-dev \
    libopenexr-dev \
    libopenjp2-7-dev \
    libopenslide-dev \
    liborc-0.4-dev \
    libpango1.0-dev \
    libpng-dev \
    libpoppler-glib-dev \
    libraw-dev \
    librtmp-dev \
    librsvg2-dev \
    libspng-dev \
    libtheora-dev \
    libtiff-dev \
    libnuma-dev \
    libvorbis-dev \
    libvpx-dev \
    libwebp-dev \
    libx264-dev \
    libx265-dev \
    libxml2-dev \
    libzstd-dev \
    pkg-config \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*